// 31 norske fiskearter med bekreftet bildemateriale
const FISH_DATA = [
  { id: "abbor", type: "Ferskvannsfisk", folder: "Abbor", nameNo: "Abbor", nameEn: "European Perch", nameLa: "Perca fluviatilis", trait: "Kjennetegn: Tydelige mørke tverrbånd, rødoransje bukfinner, pigget ryggfinne", info: "Abboren er en av Norges vanligste ferskvannsfisker og kjennetegnes lett på sine mørke tverrbånd og rødoransje finner. Den er svært tilpasningsdyktig og trives i nesten alle typer innsjøer og elver." , rarity: 5 },
  { id: "al", type: "Ferskvann- og havfisk", folder: "Al", nameNo: "Ål", nameEn: "European Eel", nameLa: "Anguilla anguilla", trait: "Kjennetegn: Slangelignende kropp, liten brystfinne, ingen bukfinner", info: "Ålen gyter i Sargassohavet og larvene driver med havstrømmene til Europa – en av naturens mest mystiske vandringer. Den er kritisk truet og fredet i mange norske vassdrag." , maxImg: 8 , rarity: 14 },
  { id: "laks", folder: "Atlantisk_laks", nameNo: "Atlantisk laks", nameEn: "Atlantic Salmon", nameLa: "Salmo salar", trait: "Kjennetegn: Sølvfarget med svarte prikker, liten fettfinne bak ryggfinnen", info: "Laksen er kjent for sin imponerende vandring – den svømmer fra havet tilbake til elven der den ble klekket for å gyte. Under sjøoppholdet skifter den farge fra brunspraglete til blank sølv." , maxImg: 8 , rarity: 8 },
  { id: "breiflabb", type: "Bunnfisk", folder: "Breiflabb", nameNo: "Breiflabb", nameEn: "Anglerfish", nameLa: "Lophius piscatorius", trait: "Kjennetegn: Enormt hode og gap, flattrykt kropp, fiskeagn på pannen", info: "Breiflabben bruker en innebygd «fiskestang» på pannen med et lysende agn for å lokke bytte inn i sitt enorme gap. Den kan svelge fisk nesten like stor som seg selv." , maxImg: 7 , rarity: 21 },
  { id: "brisling", type: "Stimfisk", folder: "Brisling", nameNo: "Brisling", nameEn: "European Sprat", nameLa: "Sprattus sprattus", trait: "Kjennetegn: Ligner sild men mindre, skarpe skjell langs buken danner en sagkant", info: "Brislingen er best kjent som «sardiner» på boks, særlig fra Stavanger-regionen. Den skilles fra sild ved sin sagformede bukkjøl.", maxImg: 6 , rarity: 13 },
  { id: "brosme", type: "Torskefisk", folder: "Brosme", nameNo: "Brosme", nameEn: "Cusk / Tusk", nameLa: "Brosme brosme", trait: "Kjennetegn: Én lang ryggfinne som løper sammen med halefinnen, enkel skjegg", info: "Brosmen er unik ved at rygg-, hale- og gatefinnen henger sammen i én sammenhengende finnekant. Den lever på hardt substrat i dypere vann." , rarity: 28 },
  { id: "gjedde", type: "Ferskvannsfisk", folder: "Gjedde", nameNo: "Gjedde", nameEn: "Northern Pike", nameLa: "Esox lucius", trait: "Kjennetegn: Lang kropp, and-lignende snute, grønnspraglete mønster", info: "Gjedden er ferskvannskongens topprovdyr og kan akselerere fra stillestående til full fart på millisekunder. Den kan bli over en meter lang og ta bytte som fugler og småpattedyr." , rarity: 15 },
  { id: "gjors", type: "Ferskvannsfisk", folder: "Gjors", nameNo: "Gjørs", nameEn: "Zander / Pike-perch", nameLa: "Sander lucioperca", trait: "Kjennetegn: Ligner abbor men uten tydelige bånd, store glassaktige øyne", info: "Gjørsen har ekstremt lysfølsomme øyne som gir den et fortrinn i grumsete eller mørkt vann. Den er Europas største abborfisk." , rarity: 17 },
  { id: "harr", type: "Laksefisk", folder: "Harr", nameNo: "Harr", nameEn: "Grayling", nameLa: "Thymallus thymallus", trait: "Kjennetegn: Stor, seilformet ryggfinne med fargerike prikker – unik blant norske fisker", info: "Harren kalles gjerne «fjellenes dronning» og trives best i kaldt, rent og oksygenrikt vann – et tegn på god vannkvalitet." , rarity: 16 },
  { id: "hvitting", type: "Torskefisk", folder: "Hvitting", nameNo: "Hvitting", nameEn: "Whiting", nameLa: "Merlangius merlangus", trait: "Kjennetegn: Mørk flekk ved brystfinnen, ingen eller svært liten skjegg", info: "Unge hvittinger søker beskyttelse under manetene til brennmaneten – de er immune mot brenncelletråder. Den er en viktig matfisk i Nordsjøen." , rarity: 9 },
  { id: "hyse", type: "Torskefisk", folder: "Hyse", nameNo: "Hyse", nameEn: "Haddock", nameLa: "Melanogrammus aeglefinus", trait: "Kjennetegn: Karakteristisk svart 'tommelfingerplett' bak brystfinnen", info: "Hysa er unik blant torskefiskene på grunn av sin svarte skulderflekk. Den foretrekker sandig bunn og spiser ofte sjøpinnsvin.", maxImg: 6 , rarity: 10 },
  { id: "kveite", type: "Flatfisk", folder: "Kveite", nameNo: "Kveite", nameEn: "Atlantic Halibut", nameLa: "Hippoglossus hippoglossus", trait: "Kjennetegn: Verdens største flatfisk, kan bli over 3 meter lang", info: "Kveiten kan veie over 300 kg og er en aktiv jeger som tar både fisk og blekksprut – uvanlig for en flatfisk. Den er ettertraktet som matfisk og en drøm for sportsfiskere.", maxImg: 6 , rarity: 19 },
  { id: "lange", type: "Torskefisk", folder: "Lange", nameNo: "Lange", nameEn: "Ling", nameLa: "Molva molva", trait: "Kjennetegn: Lang slank kropp, en lang ryggfinne, liten skjegg", info: "Langen kan bli over 2 meter lang og er like populær som tørrfisk i Portugal som torsk er i Norge." , rarity: 27 },
  { id: "lyr", type: "Torskefisk", folder: "Lyr", nameNo: "Lyr", nameEn: "Pollack", nameLa: "Pollachius pollachius", trait: "Kjennetegn: Underbitt (underkjeven stikker frem), bøyd sidelinje over brystfinnen", info: "Lyren ligner sei men skilles på sitt tydelige underbitt og den bøyde sidelinjen over brystfinnen." , maxImg: 8 , rarity: 4 },
  { id: "lysing", type: "Torskefisk", folder: "Lysing", nameNo: "Lysing", nameEn: "European Hake", nameLa: "Merluccius merluccius", trait: "Kjennetegn: Lang slank kropp, stort hode med kraftige tenner, to ryggfinner", info: "Lysingen er en nattjeger som følger byttedyr opp fra dypet om natten og er undervurdert som matfisk i Norge." , maxImg: 7 , rarity: 25 },
  { id: "makrell", type: "Pelagisk fisk", folder: "Makrell", nameNo: "Makrell", nameEn: "Atlantic Mackerel", nameLa: "Scomber scombrus", trait: "Kjennetegn: Tydelige blågrønne bølgestriper på ryggen, slank og strømlinjeformet", info: "Makrellen kan svømme i opptil 20 km/t og har ikke svømmeblære – den må svømme kontinuerlig for å holde seg flytende." , rarity: 1 },
  { id: "mort", type: "Ferskvannsfisk", folder: "Mort", nameNo: "Mort", nameEn: "Common Roach", nameLa: "Rutilus rutilus", trait: "Kjennetegn: Røde øyne, sølvskinnende kropp, rødoransje finner", info: "Morten er en av Norges aller vanligste ferskvannsfisker og finnes i nesten alle innsjøer og rolige elver. Den røde fargen på øynene er et sikkert kjennetegn." , maxImg: 9 , rarity: 11 },
  { id: "orret", type: "Laksefisk", folder: "Orret", nameNo: "Ørret", nameEn: "Brown Trout", nameLa: "Salmo trutta", trait: "Kjennetegn: Røde og svarte prikker med lysere halo, fettfinne bak ryggfinnen", info: "Ørreten finnes i tre former: bekkeørret, innsjøørret og sjøørret – alle er samme art.", maxImg: 7 , rarity: 6 },
  { id: "oyepal", type: "Torskefisk", folder: "Oyepal", nameNo: "Øyepål", nameEn: "Norway Pout", nameLa: "Trisopterus esmarkii", trait: "Kjennetegn: Store øyne, kort skjegg, mørk flekk ved brystfinnen", info: "Øyepålen har uforholdsmessig store øyne tilpasset livet i dypere vann og er en nøkkelart i Nordsjøen.", maxImg: 6 , rarity: 23 },
  { id: "piggha", type: "Hai", folder: "Piggha", nameNo: "Pigghå", nameEn: "Spiny Dogfish", nameLa: "Squalus acanthias", trait: "Kjennetegn: To ryggfinner hver med en giftig pigg foran, ingen gatefinne", info: "Pigghåen kan bli over 100 år gammel og har den lengste drektighetsperioden av alle virveldyr – to år." , maxImg: 6 , rarity: 30 },
  { id: "piggskate", type: "Skate", folder: "Piggskate", nameNo: "Piggskate", nameEn: "Thornback Ray", nameLa: "Raja clavata", trait: "Kjennetegn: Rombeformet kropp, pigger på ryggen og halen, bølgete mønster", info: "Piggskaten legger egg i karakteristiske lærlike kapsler kalt 'havfruas pung' som man kan finne på stranden. Den er den vanligste skatearten i norske farvann." , maxImg: 6 , rarity: 29 },
  { id: "rodspette", type: "Flatfisk", folder: "Rodspette", nameNo: "Rødspette", nameEn: "European Plaice", nameLa: "Pleuronectes platessa", trait: "Kjennetegn: Oransje/røde prikker på brungrå overside, begge øyne på høyre side", info: "Rødspetten er en flatfisk der begge øynene befinner seg på høyre side av kroppen etter metamorfose. De karakteristiske oransje prikkene gjør den lett gjenkjennelig." , maxImg: 7 , rarity: 12 },
  { id: "roye", type: "Laksefisk", folder: "Roye", nameNo: "Røye", nameEn: "Arctic Char", nameLa: "Salvelinus alpinus", trait: "Kjennetegn: Rød/oransje buk, lyse prikker på mørk rygg, liten munn", info: "Røya er en arktisk laksefisk som lever i de kaldeste og reneste innsjøene i Norge. Den regnes som en delikatesse og er ofte rødere i fargen enn laks og ørret." , rarity: 24 },
  { id: "sei", type: "Torskefisk", folder: "Sei", nameNo: "Sei", nameEn: "Saithe / Pollock", nameLa: "Pollachius virens", trait: "Kjennetegn: Mørk grønngrå rygg, hvit buklinje, liten eller ingen skjegg", info: "Seien skilles fra torsk ved at den har en veldig liten eller ingen skjegg under haken og en tydelig rett sidelinje." , maxImg: 7 , rarity: 3 },
  { id: "sik", type: "Laksefisk", folder: "Sik", nameNo: "Sik", nameEn: "Common Whitefish", nameLa: "Coregonus lavaretus", trait: "Kjennetegn: Sølvblank, liten munn peker nedover, liten fettfinne", info: "Siken er en laksefisk med mange lokale varianter tilpasset ulike innsjøer. Rognen er en norsk delikatesse." , rarity: 18 },
  { id: "sild", type: "Stimfisk", folder: "Sild", nameNo: "Sild", nameEn: "Atlantic Herring", nameLa: "Clupea harengus", trait: "Kjennetegn: Sølvblank, strømlinjeformet, ingen sidelinje", info: "Silda er en av verdens mest fangede fisker og danner grunnlaget for store marine næringskjeder." , rarity: 7 },
  { id: "smaflekket-rodhai", folder: "Smaflekket_rodhai", nameNo: "Småflekket rødhai", nameEn: "Small-spotted Catshark", nameLa: "Scyliorhinus canicula", trait: "Kjennetegn: Kattliknende øyne, mange små mørke prikker på beige bunn", info: "Den småflekkete rødhaien er Norges vanligste haiart og er helt ufarlig for mennesker." , maxImg: 6 , rarity: 31 },
  { id: "steinbit", type: "Bunnfisk", folder: "Steinbit", nameNo: "Steinbit", nameEn: "Atlantic Wolffish", nameLa: "Anarhichas lupus", trait: "Kjennetegn: Fryktinngytende tenner, lang åleformet kropp, ingen bukfinner", info: "Steinbiten produserer sin egen biologiske frostvæske som hindrer blodet fra å fryse i iskaldt vann." , maxImg: 7 , rarity: 22 },
  { id: "tobis", type: "Stimfisk", folder: "Tobis", nameNo: "Tobis", nameEn: "Sand Eel", nameLa: "Ammodytes tobianus", trait: "Kjennetegn: Lang og smal som en nål, graver seg ned i sand", info: "Tobisen er en nøkkelart i norske kystøkosystemer og en kritisk matkilde for laks, torsk, sjøfugl og hvaler." , maxImg: 7 , rarity: 26 },
  { id: "torsk", type: "Torskefisk", folder: "Torsk", nameNo: "Torsk", nameEn: "Atlantic Cod", nameLa: "Gadus morhua", trait: "Kjennetegn: Tre ryggfinner, to gattefinner og ett skjegg under haken", info: "Torsken er Norges viktigste matfisk og har formet norsk kultur i hundrevis av år. Den kan bli over 1,5 meter lang og veie opptil 96 kg." , maxImg: 7 , rarity: 2 },
  { id: "uer", type: "Bunnfisk", folder: "Uer", nameNo: "Uer", nameEn: "Golden Redfish", nameLa: "Sebastes norvegicus", trait: "Kjennetegn: Knallrød/oransje farge, store øyne, kraftige pigger i ryggfinnen", info: "Ueren kan bli over 200 år gammel og føder levende unger. En stor uer kan være eldre enn de fleste trær." , maxImg: 6 , rarity: 20 }
];

const FISH_BY_ID = {};
FISH_DATA.forEach(f => { FISH_BY_ID[f.id] = f; });
, confusesWith: 'Gjørs', confusionTip: 'Abbor har tydelige mørke tverrstriper'